-- CreateEnum
CREATE TYPE "Division" AS ENUM ('TEST_SERIES', 'SKILL_BUILDING', 'CAREER_COUNSELING', 'STUDY_PACKAGE', 'DPP', 'BOARD_LEVEL_TEST', 'CHAPTER_WISE_TEST');

-- AlterTable
ALTER TABLE "Opportunity" ADD COLUMN     "division" "Division" NOT NULL DEFAULT 'TEST_SERIES';
